name: 커피고래의 노트
description: Notes for thoughts and ideas
repository: hongkunyoo/hongkunyoo.github.io
meta_description: "Notes for thoughts and ideas"

markdown: kramdown
highlighter: rouge
logo: /assets/images/coffee_whale_only_bg.png
host: 0.0.0.0
port: 80
paginate: 15
baseurl: /
domain_name: 'https://hongkunyoo.github.io'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'blog url'
author:         'hongkunyoo'
