name: 커피고래의 노트
title: 커피고래의 노트
encoding: utf-8
description: "술 좋아하면 술고래, 커피 좋아하면 커피고래"
repository: hongkunyoo/hongkunyoo.github.io
meta_description: "술 좋아하면 술고래, 커피 좋아하면 커피고래"

markdown: kramdown
permalink: pretty
timezone: Asia/Seoul
highlighter: rouge
logo: /assets/images/coffee_whale_only_bg.png
host: 0.0.0.0
port: 80
paginate: 10
baseurl: /
domain_name: 'https://coffeewhale.com'
google_analytics: 'UA-63572991-1'
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

# Details for the RSS feed generator
url:            'https://coffeewhale.com'
author:         'hongkunyoo'
