apiVersion: v1
kind: Pod
metadata:
  labels:
    run: flask
  name: flask
spec:
  containers:
  - image: hongkunyoo/flask
    imagePullPolicy: Always
    name: flask
---
apiVersion: v1
kind: Service
metadata:
  name: flask
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    run: flask
  sessionAffinity: None
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask
spec:
  ingressClassName: nginx
  rules:
  - host: $HOST
    http:
      paths:
      - backend:
          service:
            name: flask
            port:
              number: 80
        path: /
        pathType: Prefix
